version: '3.8'

services:
  # ==================================================
  # PostgreSQL Database
  # ==================================================
  postgres:
    image: postgres:16-alpine
    container_name: calmou_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-meu_banco}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/calmousql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - calmou_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==================================================
  # Flask Backend API
  # ==================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calmou_backend
    restart: unless-stopped
    environment:
      FLASK_ENV: ${FLASK_ENV:-development}
      FLASK_DEBUG: ${FLASK_DEBUG:-True}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-12345}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-dev-jwt-secret-key-67890}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-meu_banco}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:*}
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    networks:
      - calmou_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ==================================================
  # pgAdmin (Opcional - para gerenciar o banco)
  # ==================================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: calmou_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@calmou.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - calmou_network
    depends_on:
      - postgres
    profiles:
      - tools  # Só inicia se usar: docker-compose --profile tools up

volumes:
  postgres_data:
    driver: local
  backend_logs:
    driver: local

networks:
  calmou_network:
    driver: bridge